# Copyright 2021 Touca, Inc. Subject to Apache-2.0 License.

name: touca-js-release

on:
  push:
    branches:
      - feature/t-244
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  publish-npm:
    name: release-publish-npm
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: yarn install
      - run: yarn build:prod
      - name: build package distributable
        run: |
          rm packages/node/README.md
          cp LICENSE packages/node/LICENSE
          cp CHANGELOG.md packages/node/CHANGELOG.md
          cp README.md packages/node/README.md
          yarn lerna version --no-git-tag-version --no-push --yes patch
          cd packages/node && npm pack
